### Write a function to compute 5/0 and use try/except to catch the exceptions

In [5]:
#function definition
def compzero():
    #try and except block
    try:
        x = 5 / 0
    except ZeroDivisionError as e:
        print(e)
#calling the function    
compzero()


division by zero


### Implement a Python program to generate all sentences where subject is in ["Americans", "Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"]. 

In [1]:
#defining the list of subjects
subjects=["Americans ","Indians"]
#defining the list of verbs
verbs=["play","watch"]
#defining the list of objects
objects=["Baseball","Cricket"]

#creating nested loops
for i in subjects:
    for j in verbs:
        for k in objects:
            print(i+" "+j+" "+k)

Americans  play Baseball
Americans  play Cricket
Americans  watch Baseball
Americans  watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


### Write a function so that the columns of the output matrix are powers of the input vector.  
### The order of the powers is determined by the increasing boolean argument. Specifically, when              increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.  
 

In [6]:
import numpy as np
#taking the vector as input
ip=(input("Enter a vector"))
lst=ip.split(",")
#converting elements of list from string to integers
for i in range(0, len(lst)): 
    lst[i] = int(lst[i])
#creating array of input vector    
x = np.array(lst)

#function to form matrix
def powcheck(x,increasing):
    #taking power as inout
    N=int(input("Enter a power"))
    
    if increasing==True:
        print(np.column_stack([x**(N-1-i) for i in range(N)]))
    else:
        print(np.column_stack([x**(i) for i in range(N)]))
    
#taking True or False as input
increasing=bool(input("Enter True or False"))
#calling the function    
powcheck(x,increasing)

Enter a vector3,5,9
Enter True or FalseFalse
Enter a power5
[[  81   27    9    3    1]
 [ 625  125   25    5    1]
 [6561  729   81    9    1]]
